apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-log
          persistentVolumeClaim:
            claimName: storage-claim
      containers:
        - name: pingpong
          image: mikael13/pingpong:0.05
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
