apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-log
          persistentVolumeClaim:
            claimName: storage-claim
      containers:
        - name: todo-app
          image: mikael13/todo-app:0.38
